server:
  port: 8085

spring:
  application:
    name: payment-processing-service
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_processing_db
    username: user_profile_user
    password: your_new_secure_password
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # Automatically create/update schema based on your @Entity classes
    show-sql: true # Log SQL queries to console for debugging
    properties:
      hibernate:
        format_sql: true