server:
  port: 8084 # Unique port for this service

spring:
  application:
    name: booking-service
  datasource: # PostgreSQL configuration
    url: jdbc:postgresql://localhost:5432/booking_db
    username: user_profile_user
    password: your_new_secure_password
    driverClassName: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # Automatically create/update schema based on your @Entity classes
    show-sql: true # Log SQL queries to console for debugging
    properties:
      hibernate:
        format_sql: true # Format logged SQL for readability

services:
  scheduling-availability-service:
    url: http://localhost:8082
  seat-reservation-service:
    url: http://localhost:8083
  payment-processing-service:
    url: http://localhost:8085
  notification-service:
    url: http://localhost:8086